name: Deploy Kong changes to PRD

on:
  workflow_call:
    secrets:
      KONNECT_PAT:
        required: true
  push:
    branches:
      - main
    paths:
      - PRD/kong/kong.yaml
      - .github/workflows/deploy-kong-PRD.yaml

jobs:

  deploy-kong:
    name: Deploy Kong to PRD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: '1.26.0'
          wrapper: false

      - name: deck sync
        run: |
          deck sync --select-tag repo-managed \
              -s PRD/kong/kong.yaml \
              --konnect-runtime-group-name KongAir-PRD \
              --konnect-token ${{ secrets.KONNECT_PAT }}
