name: Stage changes for Kong App Team

on:
  workflow_call:

jobs:

  oas-to-kong:
    name: Convert OAS to Kong configurations

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: '1.26.0'
          wrapper: false

      - name: Convert Flights API to Kong
        # In multiple steps, convert the OpenAPI Spec to a Kong declarative configuration
        #   and then patch the result with the data in the kong/patches.yaml
        #   and apply some tags
        run: |
          deck file openapi2kong -s flight-data/flights/openapi.yaml | \
            deck file patch flight-data/flights/kong/patches.yaml | \
            deck file add-tags -o config/kong/.generated/kong.yaml \
              --selector "$.services[*]" --selector "$.services[*].routes[*]" flight-data \
          deck file add-tags \
            -o config/kong/.generated/kong.yaml \
            "repo-managed"

      - name: Upload Artifacts
        # Artifacts are the files that are built along the way of the pipeline but are not committed to the repo
        uses: actions/upload-artifact@v3
        with:
          name: kong-configurations
          path: .github/artifacts/kong/*.yaml

      - name: Create PR for changed Kong Gateway Configuration
        # The only file that should be changed for this PR is config/kong/.generated/kong.yaml
        uses: peter-evans/create-pull-request@v5
        with:
          title: Stage Kong Gateway Configuration
